//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 04:25:36 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mediawiki.org/xml/export-0.8/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.lumongo.example.wikipedia.schema;
